export type CommentEmojiGroup = { id: string; label: string; emojis: string[] };

/** Curated sets for comment quick-pick (UTF-16-safe insertion uses the string as-is). */
export const COMMENT_EMOJI_GROUPS: CommentEmojiGroup[] = [
  {
    id: "smile",
    label: "表情",
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😅",
      "😂",
      "🤣",
      "😊",
      "😇",
      "🙂",
      "😉",
      "😍",
      "🥰",
      "😘",
      "😋",
      "😛",
      "😜",
      "🤪",
      "🤔",
      "😏",
      "😒",
      "🙄",
      "😮",
      "😯",
      "😲",
      "😢",
      "😭",
      "😤",
      "😡",
      "🥶",
      "🥵",
      "🤯",
      "🥳",
      "😎",
      "🤓",
      "🫠",
      "🫡",
    ],
  },
  {
    id: "gesture",
    label: "手势",
    emojis: [
      "👍",
      "👎",
      "👌",
      "🤌",
      "✌️",
      "🤞",
      "🫰",
      "🤟",
      "🤙",
      "👏",
      "🙌",
      "🫶",
      "👐",
      "🤲",
      "🤝",
      "🙏",
      "💪",
      "✍️",
      "👀",
      "🫵",
      "☝️",
      "✋",
      "🖖",
    ],
  },
  {
    id: "heart",
    label: "心",
    emojis: ["❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔", "❤️‍🔥", "💕", "💞", "💓", "💗", "💖", "💘", "💝"],
  },
  {
    id: "celebrate",
    label: "庆祝",
    emojis: ["🎉", "🎊", "✨", "🔥", "💯", "⭐", "🌟", "💫", "🏆", "🥇", "👏", "🙌", "🍻", "🥂", "🎂", "🎁"],
  },
  {
    id: "misc",
    label: "其他",
    emojis: [
      "☕",
      "🍵",
      "🍺",
      "🐱",
      "🐶",
      "🦊",
      "🐸",
      "🌿",
      "🌸",
      "🌙",
      "☀️",
      "⛅",
      "🌈",
      "📌",
      "📎",
      "✅",
      "❌",
      "❓",
      "💡",
      "📖",
      "✍️",
      "🔗",
    ],
  },
];
